import { formatDateLong } from './date'

export interface Finding {
  id: string
  severity: string
  title: string
  target: string
  discovered_at: string
}

export interface Task {
  id: string
  plugin_id: string
  tool_name: string
  target: string
  status: string
  created_at: string
  duration_seconds?: number | null
}

export interface Summary {
  total_findings: number
  critical_findings: number
  high_findings: number
  medium_findings: number
  low_findings: number
  info_findings: number
  last_scan_time: string | null
  recent_findings: Finding[]
  running_tasks: Task[]
  recent_tasks: Task[]
  scan_activity: { total: number; completed: number; running: number }
}

export function generateMarkdownReport(summary: Summary, riskLabel: string): string {
  const dateStr = new Date().toISOString()
  const formattedDate = formatDateLong(dateStr)

  let md = `# SecuScan Security Audit Report\n\n`
  md += `**Generated At:** ${formattedDate}\n`
  md += `**Overall Threat Level:** ${riskLabel.toUpperCase()}\n\n`

  md += `## 1. Executive Summary & Metrics\n\n`
  md += `This section contains a summary of the security vulnerability findings and scanning activity details.\n\n`
  md += `| Metric | Count |\n`
  md += `| :--- | :--- |\n`
  md += `| **Total Findings** | ${summary.total_findings} |\n`
  md += `| Critical Risk | ${summary.critical_findings} |\n`
  md += `| High Severity | ${summary.high_findings} |\n`
  md += `| Medium Alert | ${summary.medium_findings} |\n`
  md += `| Low Exposure | ${summary.low_findings} |\n`
  md += `| Informational | ${summary.info_findings} |\n\n`

  md += `### Scan Activity Summary\n`
  md += `- **Total Tasks Executed:** ${summary.scan_activity.total}\n`
  md += `- **Completed Tasks:** ${summary.scan_activity.completed}\n`
  md += `- **Active/Running Tasks:** ${summary.scan_activity.running}\n\n`

  md += `## 2. Recent Audit Findings\n\n`
  if (summary.recent_findings && summary.recent_findings.length > 0) {
    md += `| Title | Severity | Target | Discovered At |\n`
    md += `| :--- | :--- | :--- | :--- |\n`
    summary.recent_findings.forEach((finding) => {
      const discoveredDate = finding.discovered_at ? formatDateLong(finding.discovered_at) : 'N/A'
      md += `| ${finding.title} | **${finding.severity.toUpperCase()}** | \`${finding.target}\` | ${discoveredDate} |\n`
    })
    md += `\n`
  } else {
    md += `No recent findings detected.\n\n`
  }

  md += `## 3. Recent Scans & Task Activity\n\n`
  if (summary.recent_tasks && summary.recent_tasks.length > 0) {
    md += `| Tool/Plugin | Target | Status | Created At | Duration |\n`
    md += `| :--- | :--- | :--- | :--- | :--- |\n`
    summary.recent_tasks.forEach((task) => {
      const createdDate = task.created_at ? formatDateLong(task.created_at) : 'N/A'
      const duration = task.duration_seconds != null && task.duration_seconds > 0
        ? `${Math.round(task.duration_seconds)}s`
        : 'N/A'
      const name = task.tool_name || task.plugin_id
      md += `| ${name.toUpperCase()} | \`${task.target}\` | ${task.status.toUpperCase()} | ${createdDate} | ${duration} |\n`
    })
    md += `\n`
  } else {
    md += `No recent task activity logged.\n\n`
  }

  md += `## 4. Remediation Roadmap & Recommendations\n\n`
  const hasCriticalOrHigh = summary.critical_findings > 0 || summary.high_findings > 0
  if (hasCriticalOrHigh) {
    md += `### High Priority Action Items\n\n`
    if (summary.critical_findings > 0) {
      md += `- [ ] **Critical Alert:** Address the ${summary.critical_findings} critical vulnerability/vulnerabilities immediately to prevent host or network compromise.\n`
    }
    if (summary.high_findings > 0) {
      md += `- [ ] **High Alert:** Review and remediate the ${summary.high_findings} high-severity issue(s).\n`
    }
    md += `- [ ] Implement restrictive access controls and verify input validation across targets.\n`
  } else {
    md += `No critical or high severity vulnerabilities found. Continue regular scanning cycles to maintain security posture.\n`
  }

  md += `\n---\n*Report generated by SecuScan Workspace.*`

  return md
}
