# Generated by tmdeveloper007 - test : add unit tests for sandbox_executor resolve_sandbox_config

import pytest


class TestResolveSandboxConfig:
    """Unit tests for resolve_sandbox_config in sandbox_executor."""

    def test_returns_sandbox_config(self):
        """Returns a valid SandboxConfig regardless of inputs."""
        import backend.secuscan.sandbox_executor as se
        result = se.resolve_sandbox_config({})
        from backend.secuscan.models import SandboxConfig
        assert isinstance(result, SandboxConfig)

    def test_uses_global_defaults_when_no_override(self):
        """When override is empty, all fields come from global settings."""
        from unittest.mock import MagicMock, patch
        from backend.secuscan.models import SandboxConfig
        mock_settings = MagicMock()
        mock_settings.sandbox_timeout = 60
        mock_settings.sandbox_memory_mb = 512
        mock_settings.sandbox_max_output_bytes = 1048576
        mock_settings.sandbox_allow_network = False
        with patch("backend.secuscan.sandbox_executor.settings", mock_settings):
            result = se.resolve_sandbox_config({})
        assert result.timeout_seconds == 60
        assert result.max_memory_mb == 512
        assert result.max_output_bytes == 1048576
        assert result.allow_network is False

    def test_override_timeout_is_applied(self):
        """Explicit override values override the global defaults."""
        from unittest.mock import MagicMock, patch
        mock_settings = MagicMock()
        mock_settings.sandbox_timeout = 60
        mock_settings.sandbox_memory_mb = 512
        mock_settings.sandbox_max_output_bytes = 1048576
        mock_settings.sandbox_allow_network = False
        override = {"timeout_seconds": 120}
        with patch("backend.secuscan.sandbox_executor.settings", mock_settings):
            result = se.resolve_sandbox_config(override)
        assert result.timeout_seconds == 120
        assert result.max_memory_mb == 512

    def test_override_memory_is_applied(self):
        """Override memory value is respected."""
        from unittest.mock import MagicMock, patch
        mock_settings = MagicMock()
        mock_settings.sandbox_timeout = 60
        mock_settings.sandbox_memory_mb = 512
        mock_settings.sandbox_max_output_bytes = 1048576
        mock_settings.sandbox_allow_network = False
        override = {"max_memory_mb": 1024}
        with patch("backend.secuscan.sandbox_executor.settings", mock_settings):
            result = se.resolve_sandbox_config(override)
        assert result.max_memory_mb == 1024

    def test_override_output_bytes_is_applied(self):
        """Override max_output_bytes value is respected."""
        from unittest.mock import MagicMock, patch
        mock_settings = MagicMock()
        mock_settings.sandbox_timeout = 60
        mock_settings.sandbox_memory_mb = 512
        mock_settings.sandbox_max_output_bytes = 1048576
        mock_settings.sandbox_allow_network = False
        override = {"max_output_bytes": 2097152}
        with patch("backend.secuscan.sandbox_executor.settings", mock_settings):
            result = se.resolve_sandbox_config(override)
        assert result.max_output_bytes == 2097152

    def test_override_allow_network_is_applied(self):
        """Override allow_network value is respected."""
        from unittest.mock import MagicMock, patch
        mock_settings = MagicMock()
        mock_settings.sandbox_timeout = 60
        mock_settings.sandbox_memory_mb = 512
        mock_settings.sandbox_max_output_bytes = 1048576
        mock_settings.sandbox_allow_network = False
        override = {"allow_network": True}
        with patch("backend.secuscan.sandbox_executor.settings", mock_settings):
            result = se.resolve_sandbox_config(override)
        assert result.allow_network is True

    def test_none_fields_in_override_do_not_override(self):
        """None values in override do not override global defaults."""
        from unittest.mock import MagicMock, patch
        mock_settings = MagicMock()
        mock_settings.sandbox_timeout = 60
        mock_settings.sandbox_memory_mb = 512
        mock_settings.sandbox_max_output_bytes = 1048576
        mock_settings.sandbox_allow_network = False
        override = {
            "timeout_seconds": None,
            "allow_network": None,
        }
        with patch("backend.secuscan.sandbox_executor.settings", mock_settings):
            result = se.resolve_sandbox_config(override)
        assert result.timeout_seconds == 60
        assert result.allow_network is False

    def test_all_none_override_returns_all_defaults(self):
        """An all-None override returns all global defaults."""
        from unittest.mock import MagicMock, patch
        mock_settings = MagicMock()
        mock_settings.sandbox_timeout = 60
        mock_settings.sandbox_memory_mb = 512
        mock_settings.sandbox_max_output_bytes = 1048576
        mock_settings.sandbox_allow_network = False
        override = {
            "timeout_seconds": None,
            "max_memory_mb": None,
            "max_output_bytes": None,
            "allow_network": None,
        }
        with patch("backend.secuscan.sandbox_executor.settings", mock_settings):
            result = se.resolve_sandbox_config(override)
        assert result.timeout_seconds == 60
        assert result.max_memory_mb == 512
        assert result.max_output_bytes == 1048576
        assert result.allow_network is False
